export { default as Archivo } from './Archivo'
export type { IArchivo } from './Archivo'
export { default as Contacto } from './Contacto'
export type { IContacto } from './Contacto'
export { default as Incidente } from './Incidente'
export type { IIncidente } from './Incidente'
export { default as LogActividad } from './LogActividad'
export type { ILogActividad } from './LogActividad'
export { default as NotaPrivada } from './NotaPrivada'
export type { INotaPrivada } from './NotaPrivada'
export { default as Organización } from './Organizacion'
export type { IOrganizacion } from './Organizacion'
export { default as Poliza } from './Poliza'
export type { IPoliza } from './Poliza'
export { default as Productor } from './Productor'
export type { IProductor } from './Productor'
export { default as Respuesta } from './Respuesta'
export type { IRespuesta } from './Respuesta'
export { default as Riesgo } from './Riesgo'
export type { IRiesgo } from './Riesgo'
export { default as Siniestro } from './Siniestro'
export type { ISiniestro } from './Siniestro'
export { default as Tarea } from './Tarea'
export type { ITarea } from './Tarea'
export { default as TipoIncidente } from './TipoIncidente'
export type { ITipoIncidente } from './TipoIncidente'
